[package]
name = "linuxrecall"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
chrono = "0.4.38"
screenshot-rs = "=0.1.5"
x11 = { version = "2.21.0", features= ["all"] }
x11-dl = "2.21.0"


[build-dependencies]
pkg-config = "0.3.19"
